keys:
  - &mac ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBmMjHUkI6PGsjLVkzDbziiAkJGIpKHy6ZDC1+aAEmlR daniil@MacBook-Air-daniil.local

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
        age:
          - *mac
